### ISSUE TITLE
making per-filetype aspell mode spec configurable

### ISSUE THREAD

**Issue by sharethewisdom** [Konfekt/vim-guesslang#2]
hi, I added `elseif &l:filetype is# 'wiki' | let mode = ' --mode=html'`. Could you please add this, or consider ways for the user to configure this without changing the plugin?

thanks, this plugin is priceless!

**Comment by Konfekt** [comment]
From what I can tell, `wiki` is usually a markdown file format. Why should `mode` be set to `html` in general? 

It could make sense to turn all these pairs of filetypes and modes into a list of pairs, like
```vim
let ftmodes = [['wiki', 'html'], ['html', 'html']]
```
and then
```vim
    let mode = ''
    for ftmode in ftmodes
      if     &l:filetype is# ftmode[0] | let mode = ftmode[1] | endif
      break
   endfor
```
 Would you mind making a pull request?

**Comment by sharethewisdom** [comment]
> Would you mind making a pull request?

sure

I used quite a few html tags in wiki files like `<audio>` and `<details>`, and I noticed that for small files english was detected in stead of the written language likely because of the presence of such tags.

**Comment by Konfekt** [comment]
Thank you! The above should have read
```vim
    let mode = ''
    for ftmode in ftmodes
      if     &l:filetype is# ftmode[0]
        let mode = ftmode[1]
        break
      endif
   endfor
```
