### ISSUE TITLE
check if language dialect is available

### ISSUE THREAD

**Issue by Konfekt** [Konfekt/vim-guesslang#4]
There are some dialects that `aspell` knows about, for example `fr_fr`, but `Vim` does not.
 
Setting `&spelllang` to such an unavailable dialect triggers a warning.

Is there a way to check if a dialect is available in Vim?

**Comment by shuber2** [comment]
I am puzzled by the use case. Why would someone ask vim-detectspellang to decided whether some content is of a language (by whatever means) that is unknown to vim? That is, why is it a legitime use case to add a language unknown to vim in spellang?

**Comment by Konfekt** [comment]
It is `aspell` that detects the language behind the scenes, and the languages checked for must be those of `aspell`. On my system, for example, `aspell dicts` shows many dialects  of `de` and the single dialect `pt_br` of `pt`, but neither `de` nor `pt` itself. While `Vim` knows the dialect `de_de`, it does not know `pt_br`.

**Comment by Konfekt** [comment]
It would be nice if `Vim` fell back to the generic form in case the dialect is not available instead of triggering a warning. But maybe these dialects are available for `Vim` after all and it serves as an incentive.
