### ISSUE TITLE
Duplicate tag "aspell"

### ISSUE THREAD

**Issue by sandersantema** [Konfekt/vim-guesslang#5]
Neovim gives the following error when updating my helptags `:helpt ALL` 

`E154: Duplicate tag "aspell" in file /Users/sandersantema/.config/dein/.cache/init.vim/.dein/doc/guesslang.txt`

I believe this is related to an error in the helpfile, since I have recached my dein (plugin manager) cache. A fix would be nice so no error is displayed.

Thanks for the plugin.

**Comment by Konfekt** [comment]
Thanks for bringing this up. Should be fixed.
